# fly.toml file generated for dz6 on 2023-03-01T20:27:32+01:00

app = "dz6"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true

[mounts]
source="dz6"
destination="/data"